### ISSUE TITLE
Accidental mic when typing on Console

### ISSUE THREAD

**Issue by Vaarelsauce** [redassser/Walkie#1]
Typing things into the console that requires the "r" button will accidentally turn the walkie-talkie on. 

Solution A: It would be nice to disable the WalkieUse when on the console, because the walkie-talkie is still accessible by holding down the mouse button.

Solution B: Move the walkie hotkey to a different button, like tilde [~] or F1-F12.

**Comment by Vaarelsauce** [comment]
Also not related, but I think this mod (or at least the F to Flashlight mod) is client-sided, so it doesn't require host to have it installed.

**Comment by rpiedev** [comment]
Fixed in latest release

As for the client side thing, I did some testing and apparently its true! Both mods work client side on vanilla servers which is wild.
