### ISSUE TITLE
Walkie press button animation plays on items that are not the walkie

### ISSUE THREAD

**Issue by KingKalua808** [redassser/Walkie#4]
I'm pretty sure this is due to V45. When you press r to activate the walkie and are holding something else in your hand like a one-handed scrap or flashlight, it'll play the animation of pressing the button with that item. Not game-breaking but just a weird bug.

**Comment by rpiedev** [comment]
You may not have noticed, but this has actually always been a part of the walkie mod! It's a consequence of the activating the item when its not being held, but the item activate has an animation play, so it just plays on whatever youre holding. I thought it was funny so I left it in but I suppose I never thought about if it even should be. 
I'm open to suggestions.

**Comment by KingKalua808** [comment]
Oh wow, I never noticed it as I was using it before. I can see it as being realistic and you can imagine you are using the walkie if it's placed on your chest. If it's been here since day one then I don't have a problem with it. I guess if you wanted to add flexibility then you could do a config type of thing but ultimately it's up to you. I was also wondering if it'd be possible to add the feature of changing the key bind.

**Comment by rpiedev** [comment]
Keybinds is the next move, but I want to integrate it with the new controls remapping panel in the settings somehow so I'm gonna have to figure that out... but yeah it'll be the next update for sure

**Comment by KingKalua808** [comment]
Alright sounds good! Thanks for the quick response. I'll close this now.
