### ISSUE TITLE
Key bind issues

### ISSUE THREAD

**Issue by KingKalua808** [redassser/Walkie#5]
If you are using one of the mods and change the key bind of some other key bind like the drop key bind, it'll save that key bind for the mod and make that key the key bind but will show the key bind that was set for the mod. For example, I set my drop key bind to G and the walkie will activate when I press G and not when I press the key I set even though it shows a different key for the walkie in the settings. It seems to take the most recent key bind that was changed. Same issue applies to the flash light mod.

**Comment by rpiedev** [comment]
You are 100% correct on the cause of the issue, a bit embarrassing on my part. Easy fix will be pushed in a few

**Comment by KingKalua808** [comment]
Thank you for all the fast responses and for adding the key binds so soon after I mentioned it.

**Comment by rpiedev** [comment]
I really appreciate you bringing these issues up to me, its incredibly helpful! Update pushed, will show on thunderstore in a few
