### ISSUE TITLE
compatibility with termspeak

### ISSUE THREAD

**Issue by slovinsqui** [redassser/Walkie#8]
there are two mods that would make the terminal usage better (terminal desktop and termspeak)
termspeak makes the walkie usable when on the terminal, but only by holding left click, ignoring the R hotkey from walkie use, making the usage of the walkie talkie kinda akward when also using the terminal desktop mod, i think this would be fixed by allowing walkie use to work in terminals

**Comment by rpiedev** [comment]
Check latest release, made walkie usable in terminals when terminal desktop is installed!
